name: Build LKM

on:
  push:
    branches: ["main"]
    paths:
      - ".github/workflows/build-lkm.yml"
      - "kernel/**"
  pull_request:
    branches: ["main"]
    paths:
      - ".github/workflows/build-lkm.yml"
      - "kernel/**"
  workflow_dispatch:

jobs:
  build-lkm:
    strategy:
      matrix:
        include:
          - version: "android12-5.10"
            sub_level: 257
            os_patch_level: "2026-07"

    uses: ./.github/workflows/gki-kernel.yml
    with:
      version: ${{ matrix.version }}
      version_name: ${{ matrix.version }}.${{ matrix.sub_level }}
      tag: ${{ matrix.version }}-${{ matrix.os_patch_level }}
      os_patch_level: ${{ matrix.os_patch_level }}
      build_lkm: true
